### ISSUE TITLE
sameAs not support array

### ISSUE THREAD

**Issue by veksa** [Torann/json-ld#1]
I'm trying to do sameAs as simple array, but mapProperty support only structured data

**Comment by Torann** [comment]
Could post a snippet of what you're trying to do?

**Comment by veksa** [comment]
<?
$socials = ArrayHelper::map(Social::find()->all(), 'code', 'link');
?>
<?= \JsonLd\Context::create('organization', [
    'name' => Yii::t('app', Yii::$app->name),
    'url' => Url::to(['default/index'], true),
    'logo' => 'img/logo.png',
    'email' => Yii::$app->params['adminEmail'],
    'sameAs' => $socials
]) ?>

**Comment by Torann** [comment]
Well that's simple, _sameAs_ only accepts strings at the moment. If I have time today I'll make it accept arrays as well
