### ISSUE TITLE
How to: Multiple products

### ISSUE THREAD

**Issue by rdok-pigogo** [Torann/json-ld#21]
Let me start, by thank you for the awesome simple code you've been maintaining @Torann.

More of a question, rather than an issue :

Our system needs to create a schema, connecting a product, with it's three most popular. Thus:

https://schema.org/Product -> https://schema.org/isSimilarTo -> Many https://schema.org/Product

For one product, [no problem](https://github.com/linkwise/json-ld/commit/6b86f89f7e4911575e60e3450e2f0b6d377e256b), we're awesome.

What about when we want to connect it to many other contexts products? 

How might we go on to implement that feature?  Is this the way to go? https://github.com/Torann/json-ld/pull/20/files

Thank you in advance

**Comment by rdok-pigogo** [comment]
Future reference: the above passes the validation at https://search.google.com/structured-data/testing-tool/u/0/

**Comment by Torann** [comment]
Great work! 👍
