### ISSUE TITLE
Is it possible to have multiple authors for article?

### ISSUE THREAD

**Issue by abetwothree** [Torann/json-ld#44]
I'm trying to publish an article with multiple authors but all I get is the following without any author data.

```json
"author": {
    "@type": "Author"
},
```

Is there a way to create an array like the following answer so it looks like the json below:
https://webmasters.stackexchange.com/a/90191

```json
"author": [{
    "@type": "Person",
    "familyName": "van der Westhuizon",
    "givenName": "Jason",
    "name": "Jason van der Westhuizon"
},
{
    "@type": "Person",
    "familyName": "du Toit",
    "givenName": "Jene",
    "name": "Jene du Toit"
}]
```

Thank you!

**Comment by boly38** [comment]
Hi, 
I'm not maintainer of this repository but I recently worked on "comments", a similar issue (#41)

I think 'author' like 'comment' could be an array or a single entry. 

I dont make the test, but I'm pretty sure that the current release only support one author.

- 'Article' is a 'Creative Work' child.
- 'autor' and 'comment' are 'Creative Work' properties.

I think you will have to improve source code and suggest a pull request with following update:
- Improve 'Creative Work' for authors like I have done for comments
cf. 
https://github.com/Torann/json-ld/blob/master/src/ContextTypes/CreativeWork.php
(add a setAuthorAttribute(..) similar to addCommentAttribute(..))

- update a unit test to have 2 or N authors usecase like for the following test where we have 2 comments
https://github.com/Torann/json-ld/blob/master/tests/ContextTypes/ArticleTest.php

Of course we could certainely investigate deeper to make this pattern (array of value) available by default for all properties of a context, but I'ven't done this analysis ;)

Hope this will help/unlock you.

regards

**Comment by abetwothree** [comment]
Thank you so much for taking the time to comment extensively and make a PR to make this functionality possible.

Hopefully, the maintainer pulls your changes so this will work. Thank you so much!
